require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/asset_note_groups", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AssetNoteGroup. As you add validations to AssetNoteGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AssetNoteGroup.create! valid_attributes
      get asset_note_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      asset_note_group = AssetNoteGroup.create! valid_attributes
      get asset_note_group_url(asset_note_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_asset_note_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      asset_note_group = AssetNoteGroup.create! valid_attributes
      get edit_asset_note_group_url(asset_note_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AssetNoteGroup" do
        expect {
          post asset_note_groups_url, params: { asset_note_group: valid_attributes }
        }.to change(AssetNoteGroup, :count).by(1)
      end

      it "redirects to the created asset_note_group" do
        post asset_note_groups_url, params: { asset_note_group: valid_attributes }
        expect(response).to redirect_to(asset_note_group_url(AssetNoteGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AssetNoteGroup" do
        expect {
          post asset_note_groups_url, params: { asset_note_group: invalid_attributes }
        }.to change(AssetNoteGroup, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post asset_note_groups_url, params: { asset_note_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested asset_note_group" do
        asset_note_group = AssetNoteGroup.create! valid_attributes
        patch asset_note_group_url(asset_note_group), params: { asset_note_group: new_attributes }
        asset_note_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the asset_note_group" do
        asset_note_group = AssetNoteGroup.create! valid_attributes
        patch asset_note_group_url(asset_note_group), params: { asset_note_group: new_attributes }
        asset_note_group.reload
        expect(response).to redirect_to(asset_note_group_url(asset_note_group))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        asset_note_group = AssetNoteGroup.create! valid_attributes
        patch asset_note_group_url(asset_note_group), params: { asset_note_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested asset_note_group" do
      asset_note_group = AssetNoteGroup.create! valid_attributes
      expect {
        delete asset_note_group_url(asset_note_group)
      }.to change(AssetNoteGroup, :count).by(-1)
    end

    it "redirects to the asset_note_groups list" do
      asset_note_group = AssetNoteGroup.create! valid_attributes
      delete asset_note_group_url(asset_note_group)
      expect(response).to redirect_to(asset_note_groups_url)
    end
  end
end
