require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ir_analyses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # IrAnalysis. As you add validations to IrAnalysis, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      IrAnalysis.create! valid_attributes
      get ir_analyses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ir_analysis = IrAnalysis.create! valid_attributes
      get ir_analysis_url(ir_analysis)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ir_analysis_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ir_analysis = IrAnalysis.create! valid_attributes
      get edit_ir_analysis_url(ir_analysis)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new IrAnalysis" do
        expect {
          post ir_analyses_url, params: { ir_analysis: valid_attributes }
        }.to change(IrAnalysis, :count).by(1)
      end

      it "redirects to the created ir_analysis" do
        post ir_analyses_url, params: { ir_analysis: valid_attributes }
        expect(response).to redirect_to(ir_analysis_url(IrAnalysis.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new IrAnalysis" do
        expect {
          post ir_analyses_url, params: { ir_analysis: invalid_attributes }
        }.to change(IrAnalysis, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post ir_analyses_url, params: { ir_analysis: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ir_analysis" do
        ir_analysis = IrAnalysis.create! valid_attributes
        patch ir_analysis_url(ir_analysis), params: { ir_analysis: new_attributes }
        ir_analysis.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ir_analysis" do
        ir_analysis = IrAnalysis.create! valid_attributes
        patch ir_analysis_url(ir_analysis), params: { ir_analysis: new_attributes }
        ir_analysis.reload
        expect(response).to redirect_to(ir_analysis_url(ir_analysis))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        ir_analysis = IrAnalysis.create! valid_attributes
        patch ir_analysis_url(ir_analysis), params: { ir_analysis: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ir_analysis" do
      ir_analysis = IrAnalysis.create! valid_attributes
      expect {
        delete ir_analysis_url(ir_analysis)
      }.to change(IrAnalysis, :count).by(-1)
    end

    it "redirects to the ir_analyses list" do
      ir_analysis = IrAnalysis.create! valid_attributes
      delete ir_analysis_url(ir_analysis)
      expect(response).to redirect_to(ir_analyses_url)
    end
  end
end
